files_name: "rho_full"
save_dir: /fast_scratch_1/jbohm/cell_particle_deposit_learning/rho_processed_train_files
len_file: 6000
i_low: 0
i_high: 159
num_procs: 32
energy_threshold: 0
weight_cells: False
include_tracks: True
left_from_include_tracks: False
add_3_min_dists_and_layer: False
