events_root_file: "/fast_scratch_1/jbohm/cell_particle_deposit_learning/delta/delta_root_files/delta_full.root"
preprocessed: True
dataset: "delta"
file_len: 6000
starting_event_idx: 0
num_files_to_process: 64
save_dir: "/fast_scratch_1/jbohm/cell_particle_deposit_learning/delta/"
num_procs: 32

preprocessed_file_name: "delta_full"
i_low: 0
i_high: 64