stages:
  - test

test:
  stage: test
  image: python:3.12  # pyarrow is not compatible with Python 3.13
  before_script:
    - pip install uv
    - uv pip install -r requirements.txt
  script:
    - pytest --cov=prod --cov-report=xml --cov-report=html --junitxml=test-results.xml
    - coverage report
  artifacts:
    when: always
    paths:
      - htmlcov/             # Store HTML coverage report
      - coverage.xml         # XML coverage report for GitLab parsing
      - test-results.xml     # JUnit-style test report
    reports:
      junit: test-results.xml  # Enables GitLab Test Report UI
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml  # Enables GitLab Coverage Visualization
    expire_in: 7 days  # Keep test reports for 7 days
  coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
